# Generated by Django 5.2.10 on 2026-01-22 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_subscription_url_charfield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionitem',
            options={'verbose_name': 'Подписка → объявление', 'verbose_name_plural': 'Подписки → объявления'},
        ),
        migrations.AlterModelOptions(
            name='tariffplan',
            options={'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
        migrations.AlterModelOptions(
            name='telegramprofile',
            options={'verbose_name': 'Telegram профиль', 'verbose_name_plural': 'Telegram профили'},
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='item',
            name='external_id',
            field=models.CharField(max_length=128, verbose_name='Внешний ID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='item',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='item',
            name='raw',
            field=models.JSONField(blank=True, null=True, verbose_name='Сырые данные'),
        ),
        migrations.AlterField(
            model_name='item',
            name='source',
            field=models.CharField(default='generic', max_length=32, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.URLField(max_length=2048, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='consecutive_errors',
            field=models.PositiveIntegerField(default=0, verbose_name='Ошибок подряд'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Включена'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='last_check_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя проверка'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='last_error',
            field=models.TextField(blank=True, default='', verbose_name='Последняя ошибка'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='last_item_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя находка'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='last_success_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний успешный чек'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='rps_limit',
            field=models.PositiveSmallIntegerField(default=1, help_text='RPS (1–10 в зависимости от тарифа)', verbose_name='Лимит запросов в секунду'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='subscriptionitem',
            name='first_seen_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Впервые увидели'),
        ),
        migrations.AlterField(
            model_name='subscriptionitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item', verbose_name='Объявление'),
        ),
        migrations.AlterField(
            model_name='subscriptionitem',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Уведомлено'),
        ),
        migrations.AlterField(
            model_name='subscriptionitem',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subscription', verbose_name='Подписка'),
        ),
        migrations.AlterField(
            model_name='tariffplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='tariffplan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='tariffplan',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tariffplan',
            name='rps_limit',
            field=models.PositiveSmallIntegerField(help_text='RPS', verbose_name='Лимит запросов в секунду'),
        ),
        migrations.AlterField(
            model_name='tariffplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='telegramprofile',
            name='chat_id',
            field=models.BigIntegerField(unique=True, verbose_name='ID чата'),
        ),
        migrations.AlterField(
            model_name='telegramprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='telegramprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='telegramprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
