# Generated by Django 5.2.10 on 2026-01-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_item_options_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='pause_reason',
            field=models.TextField(blank=True, default='', verbose_name='Причина паузы'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='paused_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Пауза до'),
        ),
    ]
