# Generated by Django 5.2.10 on 2026-01-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_subscription_pause_reason_subscription_paused_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_job_enqueued_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний job enqueued_at'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_job_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Последний job_id'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_job_latency_ms',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Последняя задержка job (мс)'),
        ),
        migrations.AddField(
            model_name='telegramprofile',
            name='rps_limit',
            field=models.PositiveSmallIntegerField(default=1, help_text="Тариф/лимит клиента (1–10). Используется scheduler'ом как общий RPS на пользователя.", verbose_name='Лимит запросов в секунду (пользователь)'),
        ),
    ]
