# Generated by Django 5.2.10 on 2026-01-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_subscription_last_job_enqueued_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='check_interval_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Если > 0, проверка раз в N секунд вместо RPS. 0 = использовать RPS.', verbose_name='Интервал проверки (сек)'),
        ),
    ]
